baseURL = 'https://willfurnell.com/'
languageCode = 'en-gb'
title = 'Will Furnell'
theme = ["github.com/theNewDynamic/gohugo-theme-ananke/v2"]
enableRobotsTXT = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[menu]
[[menu.main]]
  identifier = 'home'
  name = 'Home'
  url = '/'

[[menu.main]]
  identifier = 'projects'
  name = 'Projects'
  url = '/blog'

[[menu.main]]
  identifier = 'photography'
  name = 'Photography'
  url = 'https://wills.photography'

[ananke.social.follow]
networks = [
  "bluesky",
  "github",
  "instagram"
]

[ananke.social.bluesky]
username = 'willfurnell.com'

[ananke.social.github]
username = 'willfurnell'

[ananke.social.instagram]
username = 'willfurnell'

[ananke.social.share]
disable_share = true